version: '3.7'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: n8n_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: n8n_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'         # Limits the CPU usage to 0.5 CPU
          memory: 512M        # Limits the memory usage to 512MB
        reservations:
          cpus: '0.2'         # Reserves 0.2 CPU for this service
          memory: 256M        # Reserves 256MB of memory

  n8n:
    image: n8nio/n8n:latest
    restart: always
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n_db
      DB_POSTGRESDB_USER: n8n_user
      DB_POSTGRESDB_PASSWORD: securepassword
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: securepassword123
      WEBHOOK_TUNNEL_URL: https://your-webhook-url.com
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - postgres
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'         # Limits the CPU usage to 0.5 CPU
          memory: 512M        # Limits the memory usage to 512MB
        reservations:
          cpus: '0.2'         # Reserves 0.2 CPU for this service
          memory: 256M        # Reserves 256MB of memory

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - n8n
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'         # Limits the CPU usage to 0.2 CPU
          memory: 256M        # Limits the memory usage to 256MB
        reservations:
          cpus: '0.1'         # Reserves 0.1 CPU for this service
          memory: 128M        # Reserves 128MB of memory

volumes:
  postgres_data:
  n8n_data:
